//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nttweakExtended.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nttweakExtended.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to здесь можно изменить внешний вид системы.
        /// </summary>
        public static string AppearancePageDescription {
            get {
                return ResourceManager.GetString("AppearancePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внешний вид.
        /// </summary>
        public static string AppearancePageTitle {
            get {
                return ResourceManager.GetString("AppearancePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to здесь можно установить необходимые приложения.
        /// </summary>
        public static string AppsPageDescription {
            get {
                return ResourceManager.GetString("AppsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложения.
        /// </summary>
        public static string AppsPageTitle {
            get {
                return ResourceManager.GetString("AppsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выключить.
        /// </summary>
        public static string DisableButton {
            get {
                return ResourceManager.GetString("DisableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить.
        /// </summary>
        public static string EnableButton {
            get {
                return ResourceManager.GetString("EnableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор твикера: fayzetwin.
        /// </summary>
        public static string InfoAboutAppAuthor {
            get {
                return ResourceManager.GetString("InfoAboutAppAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to здесь написана информация о приложении и твикере в целом.
        /// </summary>
        public static string InfoAboutAppDescription {
            get {
                return ResourceManager.GetString("InfoAboutAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылки на нас:.
        /// </summary>
        public static string InfoAboutAppLinks {
            get {
                return ResourceManager.GetString("InfoAboutAppLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддержать автора:.
        /// </summary>
        public static string InfoAboutAppSupportAuthor {
            get {
                return ResourceManager.GetString("InfoAboutAppSupportAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о приложении.
        /// </summary>
        public static string InfoAboutAppTitle {
            get {
                return ResourceManager.GetString("InfoAboutAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия твикера: 0.9-BETA.
        /// </summary>
        public static string InfoAboutAppVersionApp {
            get {
                return ResourceManager.GetString("InfoAboutAppVersionApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внешний вид.
        /// </summary>
        public static string MainPageAppearanceButton {
            get {
                return ResourceManager.GetString("MainPageAppearanceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложения.
        /// </summary>
        public static string MainPageAppsButton {
            get {
                return ResourceManager.GetString("MainPageAppsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С чего начнем?.
        /// </summary>
        public static string MainPageDescription {
            get {
                return ResourceManager.GetString("MainPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перезагрузить проводник.
        /// </summary>
        public static string MainPageRestartExplorerButton {
            get {
                return ResourceManager.GetString("MainPageRestartExplorerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в NTTweak!.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to здесь можно настроить твикер именно так, как вам будет лучше.
        /// </summary>
        public static string SettingsPageDescription {
            get {
                return ResourceManager.GetString("SettingsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to здесь вы можете изменить язык твикера.
        /// </summary>
        public static string SettingsPageLanguageDescription {
            get {
                return ResourceManager.GetString("SettingsPageLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string SettingsPageLanguageTitle {
            get {
                return ResourceManager.GetString("SettingsPageLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить отображение расширения файлов?.
        /// </summary>
        public static string TweakFileExtensionDisplayDescription {
            get {
                return ResourceManager.GetString("TweakFileExtensionDisplayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить отображение скрытых файлов и папок?.
        /// </summary>
        public static string TweakHiddenFilesAndFoldersDescription {
            get {
                return ResourceManager.GetString("TweakHiddenFilesAndFoldersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить отображение секунд во времени на панели задач?.
        /// </summary>
        public static string TweakSecondsTaskbarDescription {
            get {
                return ResourceManager.GetString("TweakSecondsTaskbarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello world!.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
